/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as LoginVerifyRouteImport } from './routes/login.verify'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppTradeRouteImport } from './routes/_authenticated/app.trade'
import { Route as AuthenticatedAppWithdrawRouteImport } from './routes/_authenticated/app.withdraw'
import { Route as AuthenticatedAppHistoryTradeIdRouteImport } from './routes/_authenticated/app.history.$tradeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTradeRoute = AuthenticatedAppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWithdrawRoute =
  AuthenticatedAppWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHistoryTradeIdRoute =
  AuthenticatedAppHistoryTradeIdRouteImport.update({
    id: '/$tradeId',
    path: '/$tradeId',
    getParentRoute: () => AuthenticatedAppHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/login/verify': typeof LoginVerifyRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/history': typeof AuthenticatedAppHistoryRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/trade': typeof AuthenticatedAppTradeRoute
  '/app/withdraw': typeof AuthenticatedAppWithdrawRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/history/$tradeId': typeof AuthenticatedAppHistoryTradeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login/verify': typeof LoginVerifyRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/history': typeof AuthenticatedAppHistoryRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/trade': typeof AuthenticatedAppTradeRoute
  '/app/withdraw': typeof AuthenticatedAppWithdrawRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/history/$tradeId': typeof AuthenticatedAppHistoryTradeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/login/verify': typeof LoginVerifyRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/trade': typeof AuthenticatedAppTradeRoute
  '/_authenticated/app/withdraw': typeof AuthenticatedAppWithdrawRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/history/$tradeId': typeof AuthenticatedAppHistoryTradeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/rates'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/app'
    | '/login/verify'
    | '/app/chat'
    | '/app/history'
    | '/app/notifications'
    | '/app/settings'
    | '/app/trade'
    | '/app/withdraw'
    | '/app/'
    | '/app/history/$tradeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/rates'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/login/verify'
    | '/app/chat'
    | '/app/history'
    | '/app/notifications'
    | '/app/settings'
    | '/app/trade'
    | '/app/withdraw'
    | '/app'
    | '/app/history/$tradeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/rates'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/app'
    | '/login/verify'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/history'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/trade'
    | '/_authenticated/app/withdraw'
    | '/_authenticated/app/'
    | '/_authenticated/app/history/$tradeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/login/verify': {
      id: '/login/verify'
      path: '/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trade': {
      id: '/_authenticated/app/trade'
      path: '/trade'
      fullPath: '/app/trade'
      preLoaderRoute: typeof AuthenticatedAppTradeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/withdraw': {
      id: '/_authenticated/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AuthenticatedAppWithdrawRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history/$tradeId': {
      id: '/_authenticated/app/history/$tradeId'
      path: '/$tradeId'
      fullPath: '/app/history/$tradeId'
      preLoaderRoute: typeof AuthenticatedAppHistoryTradeIdRouteImport
      parentRoute: typeof AuthenticatedAppHistoryRoute
    }
  }
}

interface AuthenticatedAppHistoryRouteChildren {
  AuthenticatedAppHistoryTradeIdRoute: typeof AuthenticatedAppHistoryTradeIdRoute
}

const AuthenticatedAppHistoryRouteChildren: AuthenticatedAppHistoryRouteChildren =
  {
    AuthenticatedAppHistoryTradeIdRoute: AuthenticatedAppHistoryTradeIdRoute,
  }

const AuthenticatedAppHistoryRouteWithChildren =
  AuthenticatedAppHistoryRoute._addFileChildren(
    AuthenticatedAppHistoryRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTradeRoute: typeof AuthenticatedAppTradeRoute
  AuthenticatedAppWithdrawRoute: typeof AuthenticatedAppWithdrawRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTradeRoute: AuthenticatedAppTradeRoute,
  AuthenticatedAppWithdrawRoute: AuthenticatedAppWithdrawRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LoginRouteChildren {
  LoginVerifyRoute: typeof LoginVerifyRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginVerifyRoute: LoginVerifyRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
